# Cosmos REST Faucet configuration

gaia_home_folder = "~/.gaia"
transactions_log = "transactions.csv"
request_timeout    = "86400"

[cosmos]
prefix         = "cosmos"
denomination   = "uatom"
binary         = "juno"

[testnets]
    [testnets.theta-testnet-001]
    node_url = "http://sentry-01.theta-testnet.polypore.xyz:26657"
    chain_id = "theta-testnet-001"
    faucet_address = "cosmos15aptdqmm7ddgtcrjvc5hs988rlrkze40l4q0he"
    daily_cap = "400000000"
    amount_to_send = "10000000"
    tx_fees = "500"
